# Generated by Django 3.0.5 on 2020-05-18 22:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200517_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
