# Generated by Django 3.0.5 on 2020-05-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20200518_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bbs',
            options={'ordering': ['-created_date']},
        ),
    ]
