# Generated by Django 3.0.5 on 2020-06-06 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20200523_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='category',
            name='bigcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.BigCategory', verbose_name='顶部分类'),
        ),
    ]
